### ISSUE TITLE
class LoRaWAN can't find ?

### ISSUE THREAD

**Issue by lancezhangsf** [jeroennijhof/LoRaWAN#2]
Hi,

import LoRaWAN
........
Traceback (most recent call last):
  File "D:/WorkSpace/pythonworkspace/LoRaWAN-master/Main.py", line 3, in <module>
    import LoRaWAN
ImportError: No module named LoRaWAN

I  want to run it ,but have some errors, it can't find the LoRaWAN class .

**Comment by jeroennijhof** [comment]
Make sure you clone this repo in your source tree. So i.e. you have a main.py importing LoRaWAN in /tmp/main.py then this repo needs to be in /tmp/LoRaWAN
